"""provenance calculation raw_provider_payload data_entitlement

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-05 23:33:01.691267

Milestone 2: the provenance spine (provenance, calculation, calculation_input),
the durable raw-response store (raw_provider_payload), and the entitlement
engine's data (data_entitlement). All five tables live in the nexus schema.

provenance.raw_payload_id and raw_provider_payload.provenance_id are a real,
intentional circular FK pair (PLAN.md 4.1/4.4). Autogenerate's plain
`op.create_table` output embedded the use_alter=True FK inline on
raw_provider_payload, which SQLAlchemy's DDL compiler silently drops from
CREATE TABLE for any use_alter constraint (verified by compiling the DDL
directly) — autogenerate did not also emit the separate ALTER TABLE that
constraint needs, so it would otherwise never be created at all. This was
hand-corrected: raw_provider_payload is created without that FK, provenance is
created afterward (both tables it references already exist), and the
raw_provider_payload -> provenance FK is added via a separate
`op.create_foreign_key` once both tables exist. Downgrade drops that
constraint before dropping either table it touches.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculation",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("formula_note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_table(
        "data_entitlement",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("legal_entity", sa.Text(), nullable=False),
        sa.Column("environment", sa.Text(), nullable=False),
        sa.Column("permitted_users", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("permitted_use", sa.Text(), nullable=False),
        sa.Column("storage_allowed", sa.Boolean(), nullable=False),
        sa.Column("retention_period_days", sa.Integer(), nullable=True),
        sa.Column("derived_data_permission", sa.Boolean(), nullable=False),
        sa.Column("ai_processing_permission", sa.Boolean(), nullable=False),
        sa.Column("embedding_permission", sa.Boolean(), nullable=False),
        sa.Column("display_permission", sa.Boolean(), nullable=False),
        sa.Column("redistribution_permission", sa.Boolean(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("contract_reference", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "environment IN ('local', 'test', 'staging', 'production')",
            name="ck_data_entitlement_environment",
        ),
        sa.CheckConstraint(
            "provider IN ('sec_edgar', 'finra_trace', 'openfigi', 'fred', 'courtlistener', 'pacer', 'admin_upload', 'sp_global_loan_pricing', 'sp_global_loan_reference', 'octus', 'bloomberg', 'lseg_lpc', 'synthetic', 'ai_generated')",
            name="ck_data_entitlement_provider",
        ),
        sa.CheckConstraint(
            "expiration_date IS NULL OR expiration_date >= effective_date",
            name="ck_data_entitlement_date_range",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_data_entitlement_lookup",
        "data_entitlement",
        ["provider", "dataset", "legal_entity", "environment"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "raw_provider_payload",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("source_record_id", sa.Text(), nullable=False),
        sa.Column("request_fingerprint", sa.Text(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("storage_object_path", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("provenance_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "provider IN ('sec_edgar', 'finra_trace', 'openfigi', 'fred', 'courtlistener', 'pacer', 'admin_upload', 'sp_global_loan_pricing', 'sp_global_loan_reference', 'octus', 'bloomberg', 'lseg_lpc', 'synthetic', 'ai_generated')",
            name="ck_raw_provider_payload_provider",
        ),
        sa.CheckConstraint(
            "payload_json IS NOT NULL OR storage_object_path IS NOT NULL",
            name="ck_raw_provider_payload_has_storage_location",
        ),
        # provenance_id's FK is added below via a separate op.create_foreign_key,
        # once the provenance table exists (see module docstring).
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_raw_provider_payload_provider_fingerprint",
        "raw_provider_payload",
        ["provider", "request_fingerprint"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "provenance",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("original_source", sa.Text(), nullable=True),
        sa.Column("source_attested_by", sa.Text(), nullable=True),
        sa.Column("source_attested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_record_id", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transformation", sa.Text(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("calculation_id", sa.UUID(), nullable=True),
        sa.Column("raw_payload_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(transformation = 'calculated') = (calculation_id IS NOT NULL)",
            name="ck_provenance_calculation_linkage",
        ),
        sa.CheckConstraint(
            "classification IN ('public', 'licensed', 'synthetic', 'ai_extracted')",
            name="ck_provenance_classification",
        ),
        sa.CheckConstraint(
            "original_source IS NULL OR original_source IN ('pacer', 'courtlistener', 'issuer_site', 'other')",
            name="ck_provenance_original_source",
        ),
        sa.CheckConstraint(
            "provider = 'admin_upload' OR original_source IS NULL",
            name="ck_provenance_original_source_requires_admin_upload",
        ),
        sa.CheckConstraint(
            "provider IN ('sec_edgar', 'finra_trace', 'openfigi', 'fred', 'courtlistener', 'pacer', 'admin_upload', 'sp_global_loan_pricing', 'sp_global_loan_reference', 'octus', 'bloomberg', 'lseg_lpc', 'synthetic', 'ai_generated')",
            name="ck_provenance_provider",
        ),
        sa.CheckConstraint(
            "transformation IN ('reported', 'calculated')", name="ck_provenance_transformation"
        ),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["nexus.calculation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["nexus.raw_provider_payload.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_provenance_calculation_id",
        "provenance",
        ["calculation_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_provenance_raw_payload_id",
        "provenance",
        ["raw_payload_id"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "calculation_input",
        sa.Column("calculation_id", sa.UUID(), nullable=False),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.Column("input_role", sa.Text(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["nexus.calculation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("calculation_id", "provenance_id"),
        schema="nexus",
    )
    op.create_index(
        "ix_calculation_input_provenance_id",
        "calculation_input",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    # hand-added: see module docstring — provenance now exists, so this FK can
    # finally be created; SQLAlchemy's DDL compiler silently drops any
    # use_alter=True constraint from an inline CREATE TABLE, so this could not
    # have been included above.
    op.create_foreign_key(
        "fk_raw_provider_payload_provenance_id",
        "raw_provider_payload",
        "provenance",
        ["provenance_id"],
        ["id"],
        source_schema="nexus",
        referent_schema="nexus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # hand-added: the FK below must be dropped before dropping either table it
    # touches, or PostgreSQL refuses the DROP TABLE with a dependency error.
    op.drop_constraint(
        "fk_raw_provider_payload_provenance_id",
        "raw_provider_payload",
        schema="nexus",
        type_="foreignkey",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_calculation_input_provenance_id", table_name="calculation_input", schema="nexus"
    )
    op.drop_table("calculation_input", schema="nexus")
    op.drop_index("ix_provenance_raw_payload_id", table_name="provenance", schema="nexus")
    op.drop_index("ix_provenance_calculation_id", table_name="provenance", schema="nexus")
    op.drop_table("provenance", schema="nexus")
    op.drop_index(
        "ix_raw_provider_payload_provider_fingerprint",
        table_name="raw_provider_payload",
        schema="nexus",
    )
    op.drop_table("raw_provider_payload", schema="nexus")
    op.drop_index("ix_data_entitlement_lookup", table_name="data_entitlement", schema="nexus")
    op.drop_table("data_entitlement", schema="nexus")
    op.drop_table("calculation", schema="nexus")
    # ### end Alembic commands ###
