"""issuer and financial_fact

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-06 00:09:35.584950

Milestone 3: the first two canonical business-entity tables (PLAN.md section
4.5), populated end-to-end by the SEC EDGAR provider (Provider -> DTO ->
Normalizer -> Canonical Object -> Repository -> Postgres, PLAN.md section 18
step 3). No circular FK here (unlike migration 0002's provenance <->
raw_provider_payload) — issuer depends only on provenance, financial_fact only
on issuer and provenance — so this one didn't need the use_alter treatment.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issuer",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("cik", sa.Text(), nullable=True),
        sa.Column("lei", sa.Text(), nullable=True),
        sa.Column("ticker", sa.Text(), nullable=True),
        sa.Column("sic", sa.Text(), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index("ix_issuer_cik", "issuer", ["cik"], unique=True, schema="nexus")
    op.create_table(
        "financial_fact",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("concept", sa.Text(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("fiscal_period", sa.Text(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("form_type", sa.Text(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("accession_no", sa.Text(), nullable=False),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "form_type IN ('10-K', '10-Q', '8-K', '6-K', '20-F')",
            name="ck_financial_fact_form_type",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_financial_fact_dedup",
        "financial_fact",
        ["issuer_id", "concept", "accession_no", "fiscal_year", "fiscal_period"],
        unique=True,
        schema="nexus",
    )
    op.create_index(
        "ix_financial_fact_issuer_id", "financial_fact", ["issuer_id"], unique=False, schema="nexus"
    )
    op.create_index(
        "ix_financial_fact_provenance_id",
        "financial_fact",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_financial_fact_provenance_id", table_name="financial_fact", schema="nexus")
    op.drop_index("ix_financial_fact_issuer_id", table_name="financial_fact", schema="nexus")
    op.drop_index("ix_financial_fact_dedup", table_name="financial_fact", schema="nexus")
    op.drop_table("financial_fact", schema="nexus")
    op.drop_index("ix_issuer_cik", table_name="issuer", schema="nexus")
    op.drop_table("issuer", schema="nexus")
    # ### end Alembic commands ###
