"""security table and issuer synthetic columns

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-06 00:41:31.448226

Milestone 4: the `security` canonical table (PLAN.md 4.5) plus the
`is_synthetic`/`synthetic_reason` synthetic-flag columns on `issuer` (4.5's
"synthetic_flag" pattern) — added now because Milestone 4 is the first to
create any synthetic issuer (the leveraged loan generator's fictional demo
companies). `issuer` already has one real, committed row (Apple Inc., from
Milestone 3); `ADD COLUMN ... NOT NULL DEFAULT false` backfills it safely.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("instrument_type", sa.Text(), nullable=False),
        sa.Column("seniority", sa.Text(), nullable=True),
        sa.Column("lien_position", sa.Text(), nullable=True),
        sa.Column("secured", sa.Boolean(), nullable=True),
        sa.Column("cusip", sa.Text(), nullable=True),
        sa.Column("isin", sa.Text(), nullable=True),
        sa.Column("figi", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column("coupon", sa.Numeric(), nullable=True),
        sa.Column("amount_outstanding", sa.Numeric(), nullable=True),
        sa.Column("benchmark", sa.Text(), nullable=True),
        sa.Column("spread", sa.Numeric(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("synthetic_reason", sa.Text(), nullable=True),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "instrument_type IN ('bond', 'loan', 'equity')", name="ck_security_instrument_type"
        ),
        sa.CheckConstraint(
            "seniority IS NULL OR seniority IN ('first_lien', 'second_lien', 'senior_unsecured', 'subordinated', 'preferred', 'common')",
            name="ck_security_seniority",
        ),
        sa.CheckConstraint(
            "is_synthetic OR synthetic_reason IS NULL",
            name="ck_security_synthetic_reason_requires_is_synthetic",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_security_cusip",
        "security",
        ["cusip"],
        unique=True,
        schema="nexus",
        postgresql_where=sa.text("cusip IS NOT NULL"),
    )
    op.create_index(
        "ix_security_instrument_type", "security", ["instrument_type"], unique=False, schema="nexus"
    )
    op.create_index(
        "ix_security_isin",
        "security",
        ["isin"],
        unique=True,
        schema="nexus",
        postgresql_where=sa.text("isin IS NOT NULL"),
    )
    op.create_index(
        "ix_security_issuer_id", "security", ["issuer_id"], unique=False, schema="nexus"
    )
    op.create_index(
        "ix_security_provenance_id", "security", ["provenance_id"], unique=False, schema="nexus"
    )
    op.add_column(
        "issuer",
        sa.Column("is_synthetic", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        schema="nexus",
    )
    op.add_column("issuer", sa.Column("synthetic_reason", sa.Text(), nullable=True), schema="nexus")
    op.create_check_constraint(
        "ck_issuer_synthetic_reason_requires_is_synthetic",
        "issuer",
        "is_synthetic OR synthetic_reason IS NULL",
        schema="nexus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_issuer_synthetic_reason_requires_is_synthetic", "issuer", schema="nexus", type_="check"
    )
    op.drop_column("issuer", "synthetic_reason", schema="nexus")
    op.drop_column("issuer", "is_synthetic", schema="nexus")
    op.drop_index("ix_security_provenance_id", table_name="security", schema="nexus")
    op.drop_index("ix_security_issuer_id", table_name="security", schema="nexus")
    op.drop_index(
        "ix_security_isin",
        table_name="security",
        schema="nexus",
        postgresql_where=sa.text("isin IS NOT NULL"),
    )
    op.drop_index("ix_security_instrument_type", table_name="security", schema="nexus")
    op.drop_index(
        "ix_security_cusip",
        table_name="security",
        schema="nexus",
        postgresql_where=sa.text("cusip IS NOT NULL"),
    )
    op.drop_table("security", schema="nexus")
    # ### end Alembic commands ###
