"""figi unique index and fred tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-06 10:00:01.490230

Milestone 5: `fred_series_registry` + `fred_observation` (PLAN.md 4.5), and a
partial unique index on `security.figi` mirroring the existing `cusip`/`isin`
ones — Milestone 5 is the first to actually populate `figi` (via the OpenFIGI
adapter), so idempotent re-ingestion needs it now.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fred_series_registry",
        sa.Column("series_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("units", sa.Text(), nullable=False),
        sa.Column("frequency", sa.Text(), nullable=False),
        sa.Column("discontinued", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "redistribution_allowed",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("series_id"),
        schema="nexus",
    )
    op.create_table(
        "fred_observation",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("series_id", sa.Text(), nullable=False),
        sa.Column("obs_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["provenance_id"], ["nexus.provenance.id"]),
        sa.ForeignKeyConstraint(["series_id"], ["nexus.fred_series_registry.series_id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_fred_observation_dedup",
        "fred_observation",
        ["series_id", "obs_date"],
        unique=True,
        schema="nexus",
    )
    op.create_index(
        "ix_fred_observation_provenance_id",
        "fred_observation",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_fred_observation_series_id",
        "fred_observation",
        ["series_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_security_figi",
        "security",
        ["figi"],
        unique=True,
        schema="nexus",
        postgresql_where=sa.text("figi IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_security_figi",
        table_name="security",
        schema="nexus",
        postgresql_where=sa.text("figi IS NOT NULL"),
    )
    op.drop_index("ix_fred_observation_series_id", table_name="fred_observation", schema="nexus")
    op.drop_index(
        "ix_fred_observation_provenance_id", table_name="fred_observation", schema="nexus"
    )
    op.drop_index("ix_fred_observation_dedup", table_name="fred_observation", schema="nexus")
    op.drop_table("fred_observation", schema="nexus")
    op.drop_table("fred_series_registry", schema="nexus")
    # ### end Alembic commands ###
