"""capital structure position

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-06 13:22:48.292688

Milestone 6: `capital_structure_position` (PLAN.md 4.6) — the table backing
the Capital Structure section of the Issuer Detail workspace: one row per
layer of an issuer's debt-and-equity stack, ordered top (most senior) to
bottom by `rank_order`. `security_id` is nullable (a revolver or equity layer
may have no CUSIP-bearing `security` row); `enterprise_value_coverage` /
`illustrative_recovery` are optional and, when set, require `recovery_scenario`
to be set too (`ck_..._recovery_requires_scenario`) — PLAN.md section 7's hard
labeling rule enforced at the schema level, not just in the UI.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capital_structure_position",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=True),
        sa.Column("layer_name", sa.Text(), nullable=False),
        sa.Column("rank_order", sa.Integer(), nullable=False),
        sa.Column("instrument_type", sa.Text(), nullable=False),
        sa.Column("seniority", sa.Text(), nullable=True),
        sa.Column("lien_position", sa.Text(), nullable=True),
        sa.Column("secured", sa.Boolean(), nullable=False),
        sa.Column("guarantor_scope", sa.Text(), nullable=True),
        sa.Column("amount_outstanding", sa.Numeric(), nullable=False),
        sa.Column("currency", sa.Text(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column("price", sa.Numeric(), nullable=True),
        sa.Column("enterprise_value_coverage", sa.Numeric(), nullable=True),
        sa.Column("illustrative_recovery", sa.Numeric(), nullable=True),
        sa.Column("recovery_scenario", sa.Text(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("synthetic_reason", sa.Text(), nullable=True),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "instrument_type IN ('revolver', 'first_lien_loan', 'first_lien_notes', 'second_lien', 'unsecured', 'subordinated', 'preferred_equity', 'common_equity')",
            name="ck_capstruct_position_instrument_type",
        ),
        sa.CheckConstraint(
            "seniority IS NULL OR seniority IN ('first_lien', 'second_lien', 'senior_unsecured', 'subordinated', 'preferred', 'common')",
            name="ck_capstruct_position_seniority",
        ),
        sa.CheckConstraint(
            "(enterprise_value_coverage IS NULL AND illustrative_recovery IS NULL) OR recovery_scenario IS NOT NULL",
            name="ck_capstruct_position_recovery_requires_scenario",
        ),
        sa.CheckConstraint(
            "is_synthetic OR synthetic_reason IS NULL",
            name="ck_capstruct_position_synth_reason_requires_synth",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["nexus.security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_capital_structure_position_issuer_id",
        "capital_structure_position",
        ["issuer_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_capital_structure_position_issuer_rank",
        "capital_structure_position",
        ["issuer_id", "rank_order"],
        unique=True,
        schema="nexus",
    )
    op.create_index(
        "ix_capital_structure_position_provenance_id",
        "capital_structure_position",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_capital_structure_position_security_id",
        "capital_structure_position",
        ["security_id"],
        unique=False,
        schema="nexus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_capital_structure_position_security_id",
        table_name="capital_structure_position",
        schema="nexus",
    )
    op.drop_index(
        "ix_capital_structure_position_provenance_id",
        table_name="capital_structure_position",
        schema="nexus",
    )
    op.drop_index(
        "ix_capital_structure_position_issuer_rank",
        table_name="capital_structure_position",
        schema="nexus",
    )
    op.drop_index(
        "ix_capital_structure_position_issuer_id",
        table_name="capital_structure_position",
        schema="nexus",
    )
    op.drop_table("capital_structure_position", schema="nexus")
    # ### end Alembic commands ###
