"""research universes and filing monitor

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-06 15:46:56.111488

Milestone 6.5 (PLAN.md section 24): `collection` / `collection_membership`
(Research Universes, generalizing the approved watchlist shape per ADR-016),
`sec_filing`, `filing_monitor_run`, `research_evidence` (provider-agnostic
evidence, ADR-018 — not `distress_evidence`), and `alert_event` (first real
implementation of PLAN.md 4.11's approved shape, redesigned around Evidence
rather than SEC filings). No circular FKs this time — table creation order
falls out naturally from autogenerate: collection -> filing_monitor_run ->
alert_event -> collection_membership -> sec_filing -> research_evidence.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("collection_type", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), server_default=sa.text("'organization'"), nullable=False),
        sa.Column("owner_user_id", sa.Text(), nullable=True),
        sa.Column("visibility", sa.Text(), server_default=sa.text("'public'"), nullable=False),
        sa.Column("curation_method", sa.Text(), nullable=False),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.Text(), nullable=True),
        sa.Column("verification_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_refresh_source", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "collection_type IN ('research_universe', 'watchlist', 'benchmark')",
            name="ck_collection_type",
        ),
        sa.CheckConstraint(
            "curation_method IN ('manual_curated', 'system_seeded', 'user_created')",
            name="ck_collection_curation_method",
        ),
        sa.CheckConstraint(
            "priority IS NULL OR priority IN ('critical', 'high', 'medium', 'low')",
            name="ck_collection_priority",
        ),
        sa.CheckConstraint(
            "scope IN ('organization', 'personal', 'team')", name="ck_collection_scope"
        ),
        sa.CheckConstraint(
            "verification_status IN ('verified', 'partial', 'unverified')",
            name="ck_collection_verification_status",
        ),
        sa.CheckConstraint(
            "visibility IN ('public', 'private', 'team')", name="ck_collection_visibility"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_collection_collection_type",
        "collection",
        ["collection_type"],
        unique=False,
        schema="nexus",
    )
    op.create_index("ix_collection_slug", "collection", ["slug"], unique=True, schema="nexus")
    op.create_table(
        "filing_monitor_run",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("previous_watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resulting_watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issuers_checked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("filings_discovered", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("filings_processed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("alerts_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("errors_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("backfill_lookback_days", sa.Integer(), nullable=True),
        sa.Column("is_backfill", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('baseline', 'delta', 'backfill')", name="ck_filing_monitor_run_mode"
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'completed_with_errors', 'failed', 'baseline_established')",
            name="ck_filing_monitor_run_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_table(
        "alert_event",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bundle_key", sa.Text(), nullable=False),
        sa.Column("primary_evidence_provider", sa.Text(), nullable=False),
        sa.Column("primary_source_label", sa.Text(), nullable=False),
        sa.Column("primary_source_url", sa.Text(), nullable=True),
        sa.Column("detection_method", sa.Text(), nullable=False),
        sa.Column("ai_assisted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'new'"), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Text(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_by", sa.Text(), nullable=True),
        sa.Column("dismissal_reason", sa.Text(), nullable=True),
        sa.Column("is_backfill", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(dismissed_at IS NULL AND dismissed_by IS NULL) OR status = 'dismissed'",
            name="ck_alert_event_dismissed_requires_status",
        ),
        sa.CheckConstraint(
            "detection_method IN ('deterministic', 'ai_assisted')",
            name="ck_alert_event_detection_method",
        ),
        sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name="ck_alert_event_severity"),
        sa.CheckConstraint(
            "status IN ('new', 'acknowledged', 'dismissed')", name="ck_alert_event_status"
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_alert_event_bundle_key", "alert_event", ["bundle_key"], unique=False, schema="nexus"
    )
    op.create_index(
        "ix_alert_event_issuer_id", "alert_event", ["issuer_id"], unique=False, schema="nexus"
    )
    op.create_index(
        "ix_alert_event_provenance_id",
        "alert_event",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_alert_event_status", "alert_event", ["status"], unique=False, schema="nexus"
    )
    op.create_table(
        "collection_membership",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("rationale_as_of_date", sa.Date(), nullable=True),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.Column(
            "supporting_provenance_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("added_by", sa.Text(), nullable=True),
        sa.Column("system_seeded", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "verification_status IN ('verified', 'partial', 'unverified')",
            name="ck_collection_membership_verification_status",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["nexus.collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "issuer_id", name="uq_collection_membership_pair"),
        schema="nexus",
    )
    op.create_index(
        "ix_collection_membership_collection_id",
        "collection_membership",
        ["collection_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_collection_membership_issuer_id",
        "collection_membership",
        ["issuer_id"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "sec_filing",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("accession_no", sa.Text(), nullable=False),
        sa.Column("form_type", sa.Text(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("period_of_report", sa.Date(), nullable=True),
        sa.Column("is_amendment", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("primary_document", sa.Text(), nullable=True),
        sa.Column("primary_document_url", sa.Text(), nullable=True),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_sec_filing_accession_no", "sec_filing", ["accession_no"], unique=True, schema="nexus"
    )
    op.create_index(
        "ix_sec_filing_issuer_id", "sec_filing", ["issuer_id"], unique=False, schema="nexus"
    )
    op.create_index(
        "ix_sec_filing_provenance_id", "sec_filing", ["provenance_id"], unique=False, schema="nexus"
    )
    op.create_table(
        "research_evidence",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("evidence_provider", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("filing_id", sa.UUID(), nullable=True),
        sa.Column("evidence_type", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("source_section", sa.Text(), nullable=True),
        sa.Column("source_item", sa.Text(), nullable=True),
        sa.Column("matched_rule", sa.Text(), nullable=False),
        sa.Column("evidence_excerpt", sa.Text(), nullable=False),
        sa.Column("evidence_start_offset", sa.Integer(), nullable=True),
        sa.Column("evidence_end_offset", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=True),
        sa.Column("detection_method", sa.Text(), nullable=False),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "review_status", sa.Text(), server_default=sa.text("'unreviewed'"), nullable=False
        ),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "detection_method IN ('deterministic', 'ai_assisted')",
            name="ck_research_evidence_detection_method",
        ),
        sa.CheckConstraint(
            "evidence_type IN ('bankruptcy_or_receivership', 'chapter_11', 'chapter_7', 'default_or_missed_payment', 'covenant_breach', 'debt_acceleration', 'going_concern', 'substantial_doubt', 'liquidity_warning', 'restructuring_advisor', 'restructuring_support_agreement', 'exchange_offer', 'liability_management_transaction', 'debt_amendment', 'maturity_extension', 'refinancing', 'dip_financing', 'emergency_financing', 'material_asset_sale', 'delisting_notice', 'workforce_reduction', 'facility_closure', 'material_impairment', 'auditor_resignation', 'adverse_audit_development', 'strategic_alternatives')",
            name="ck_research_evidence_type",
        ),
        sa.CheckConstraint(
            "review_status IN ('unreviewed', 'confirmed', 'rejected')",
            name="ck_research_evidence_review_status",
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high')", name="ck_research_evidence_severity"
        ),
        sa.ForeignKeyConstraint(
            ["filing_id"],
            ["nexus.sec_filing.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_research_evidence_filing_id",
        "research_evidence",
        ["filing_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_research_evidence_issuer_id",
        "research_evidence",
        ["issuer_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_research_evidence_provenance_id",
        "research_evidence",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_research_evidence_provenance_id", table_name="research_evidence", schema="nexus"
    )
    op.drop_index("ix_research_evidence_issuer_id", table_name="research_evidence", schema="nexus")
    op.drop_index("ix_research_evidence_filing_id", table_name="research_evidence", schema="nexus")
    op.drop_table("research_evidence", schema="nexus")
    op.drop_index("ix_sec_filing_provenance_id", table_name="sec_filing", schema="nexus")
    op.drop_index("ix_sec_filing_issuer_id", table_name="sec_filing", schema="nexus")
    op.drop_index("ix_sec_filing_accession_no", table_name="sec_filing", schema="nexus")
    op.drop_table("sec_filing", schema="nexus")
    op.drop_index(
        "ix_collection_membership_issuer_id", table_name="collection_membership", schema="nexus"
    )
    op.drop_index(
        "ix_collection_membership_collection_id", table_name="collection_membership", schema="nexus"
    )
    op.drop_table("collection_membership", schema="nexus")
    op.drop_index("ix_alert_event_status", table_name="alert_event", schema="nexus")
    op.drop_index("ix_alert_event_provenance_id", table_name="alert_event", schema="nexus")
    op.drop_index("ix_alert_event_issuer_id", table_name="alert_event", schema="nexus")
    op.drop_index("ix_alert_event_bundle_key", table_name="alert_event", schema="nexus")
    op.drop_table("alert_event", schema="nexus")
    op.drop_table("filing_monitor_run", schema="nexus")
    op.drop_index("ix_collection_slug", table_name="collection", schema="nexus")
    op.drop_index("ix_collection_collection_type", table_name="collection", schema="nexus")
    op.drop_table("collection", schema="nexus")
    # ### end Alembic commands ###
