"""court dockets

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-06 19:17:44.960920

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "court_docket",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("courtlistener_docket_id", sa.BigInteger(), nullable=False),
        sa.Column("court", sa.Text(), nullable=False),
        sa.Column("docket_number", sa.Text(), nullable=False),
        sa.Column("case_name", sa.Text(), nullable=False),
        sa.Column("nature_of_suit", sa.Text(), nullable=True),
        sa.Column("chapter", sa.Text(), nullable=True),
        sa.Column("date_filed", sa.Date(), nullable=True),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_court_docket_courtlistener_docket_id",
        "court_docket",
        ["courtlistener_docket_id"],
        unique=True,
        schema="nexus",
    )
    op.create_index(
        "ix_court_docket_issuer_id", "court_docket", ["issuer_id"], unique=False, schema="nexus"
    )
    op.create_index(
        "ix_court_docket_provenance_id",
        "court_docket",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "court_docket_entry",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("docket_id", sa.UUID(), nullable=False),
        sa.Column("courtlistener_entry_id", sa.BigInteger(), nullable=False),
        sa.Column("entry_number", sa.Integer(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "document_available", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["docket_id"],
            ["nexus.court_docket.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_court_docket_entry_courtlistener_entry_id",
        "court_docket_entry",
        ["courtlistener_entry_id"],
        unique=True,
        schema="nexus",
    )
    op.create_index(
        "ix_court_docket_entry_docket_id",
        "court_docket_entry",
        ["docket_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_court_docket_entry_provenance_id",
        "court_docket_entry",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "docket_document",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("docket_entry_id", sa.UUID(), nullable=False),
        sa.Column("courtlistener_document_id", sa.BigInteger(), nullable=False),
        sa.Column("availability", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("is_sealed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("recap_document_url", sa.Text(), nullable=True),
        sa.Column("raw_payload_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by", sa.Text(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provenance_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (is_sealed AND availability = 'recap_available')",
            name="ck_docket_document_sealed_never_recap_available",
        ),
        sa.CheckConstraint(
            "availability IN ('recap_available', 'unavailable_admin_upload_needed', 'admin_uploaded')",
            name="ck_docket_document_availability",
        ),
        sa.ForeignKeyConstraint(
            ["docket_entry_id"],
            ["nexus.court_docket_entry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["nexus.raw_provider_payload.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_docket_document_courtlistener_document_id",
        "docket_document",
        ["courtlistener_document_id"],
        unique=True,
        schema="nexus",
    )
    op.create_index(
        "ix_docket_document_docket_entry_id",
        "docket_document",
        ["docket_entry_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_docket_document_provenance_id",
        "docket_document",
        ["provenance_id"],
        unique=False,
        schema="nexus",
    )
    op.add_column(
        "research_evidence", sa.Column("docket_entry_id", sa.UUID(), nullable=True), schema="nexus"
    )
    op.create_index(
        "ix_research_evidence_docket_entry_id",
        "research_evidence",
        ["docket_entry_id"],
        unique=False,
        schema="nexus",
    )
    op.create_foreign_key(
        "fk_research_evidence_docket_entry_id",
        "research_evidence",
        "court_docket_entry",
        ["docket_entry_id"],
        ["id"],
        source_schema="nexus",
        referent_schema="nexus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_research_evidence_docket_entry_id",
        "research_evidence",
        schema="nexus",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_research_evidence_docket_entry_id", table_name="research_evidence", schema="nexus"
    )
    op.drop_column("research_evidence", "docket_entry_id", schema="nexus")
    op.drop_index("ix_docket_document_provenance_id", table_name="docket_document", schema="nexus")
    op.drop_index(
        "ix_docket_document_docket_entry_id", table_name="docket_document", schema="nexus"
    )
    op.drop_index(
        "ix_docket_document_courtlistener_document_id", table_name="docket_document", schema="nexus"
    )
    op.drop_table("docket_document", schema="nexus")
    op.drop_index(
        "ix_court_docket_entry_provenance_id", table_name="court_docket_entry", schema="nexus"
    )
    op.drop_index(
        "ix_court_docket_entry_docket_id", table_name="court_docket_entry", schema="nexus"
    )
    op.drop_index(
        "ix_court_docket_entry_courtlistener_entry_id",
        table_name="court_docket_entry",
        schema="nexus",
    )
    op.drop_table("court_docket_entry", schema="nexus")
    op.drop_index("ix_court_docket_provenance_id", table_name="court_docket", schema="nexus")
    op.drop_index("ix_court_docket_issuer_id", table_name="court_docket", schema="nexus")
    op.drop_index(
        "ix_court_docket_courtlistener_docket_id", table_name="court_docket", schema="nexus"
    )
    op.drop_table("court_docket", schema="nexus")
    # ### end Alembic commands ###
