"""milestone 7.5 market discovery and enrichment status

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-07 08:16:02.442176

Milestone 7.5 (PLAN.md): `market_discovery_run` / `market_discovery_candidate`
(market-wide SEC full-text-search discovery, watermarked separately from
`filing_monitor_run`'s known-issuer refresh; `(cik, accession_no)` is a
source-identity/dedup key, `rule_version` keeps deliberate reprocessing
possible without duplicating rows), `issuer_enrichment_status` (per-issuer/
provider enrichment tracking distinguishing "no data" from "never checked"),
and `court_docket_link_attempt` (full audit trail for ADR-020's automatic
CourtListener docket-linking signal evaluation). No existing table changed;
autogenerate detected zero drift elsewhere.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_discovery_run",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("window_start_date", sa.Date(), nullable=False),
        sa.Column("window_end_date", sa.Date(), nullable=False),
        sa.Column("previous_watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resulting_watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("queries_executed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("filings_examined", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("candidate_filings", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "issuers_resolved_existing", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "issuers_resolved_new", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("issuers_ambiguous", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("issuers_rejected", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("evidence_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("alerts_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("errors_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('baseline', 'delta', 'backfill')", name="ck_market_discovery_run_mode"
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'completed_with_errors', 'failed', 'baseline_established')",
            name="ck_market_discovery_run_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_table(
        "issuer_enrichment_status",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_found", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_classification", sa.Text(), nullable=True),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'complete', 'no_data', 'ambiguous', 'manual_review_required', 'failed_retryable', 'failed_permanent', 'blocked_entitlement', 'unavailable', 'unsupported')",
            name="ck_issuer_enrichment_status_status",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "issuer_id", "provider", name="uq_issuer_enrichment_status_issuer_provider"
        ),
        schema="nexus",
    )
    op.create_index(
        "ix_issuer_enrichment_status_issuer_id",
        "issuer_enrichment_status",
        ["issuer_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_issuer_enrichment_status_provider",
        "issuer_enrichment_status",
        ["provider"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "market_discovery_candidate",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("discovery_run_id", sa.UUID(), nullable=False),
        sa.Column("cik", sa.Text(), nullable=False),
        sa.Column("accession_no", sa.Text(), nullable=False),
        sa.Column("form_type", sa.Text(), nullable=False),
        sa.Column("file_date", sa.Date(), nullable=False),
        sa.Column("matched_query", sa.Text(), nullable=False),
        sa.Column("sec_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolution_outcome", sa.Text(), nullable=False),
        sa.Column("resolution_reason", sa.Text(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=True),
        sa.Column("layer1_matched", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "evidence_created", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("provenance_id", sa.UUID(), nullable=True),
        sa.Column("rule_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resolution_outcome IN ('matched_existing', 'verified_new', 'ambiguous', 'rejected', 'unresolved')",
            name="ck_market_discovery_candidate_resolution_outcome",
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["nexus.market_discovery_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["nexus.provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cik", "accession_no", name="uq_market_discovery_candidate_cik_accession"
        ),
        schema="nexus",
    )
    op.create_index(
        "ix_market_discovery_candidate_discovery_run_id",
        "market_discovery_candidate",
        ["discovery_run_id"],
        unique=False,
        schema="nexus",
    )
    op.create_index(
        "ix_market_discovery_candidate_issuer_id",
        "market_discovery_candidate",
        ["issuer_id"],
        unique=False,
        schema="nexus",
    )
    op.create_table(
        "court_docket_link_attempt",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("query_used", sa.Text(), nullable=False),
        sa.Column("candidate_courtlistener_docket_id", sa.BigInteger(), nullable=True),
        sa.Column("match_outcome", sa.Text(), nullable=False),
        sa.Column("match_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("linked_docket_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_outcome IN ('verified_docket_match', 'checked_no_relevant_docket', 'ambiguous_manual_review', 'unavailable', 'retryable_failure')",
            name="ck_court_docket_link_attempt_match_outcome",
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["nexus.issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linked_docket_id"],
            ["nexus.court_docket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="nexus",
    )
    op.create_index(
        "ix_court_docket_link_attempt_issuer_id",
        "court_docket_link_attempt",
        ["issuer_id"],
        unique=False,
        schema="nexus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_court_docket_link_attempt_issuer_id",
        table_name="court_docket_link_attempt",
        schema="nexus",
    )
    op.drop_table("court_docket_link_attempt", schema="nexus")
    op.drop_index(
        "ix_market_discovery_candidate_issuer_id",
        table_name="market_discovery_candidate",
        schema="nexus",
    )
    op.drop_index(
        "ix_market_discovery_candidate_discovery_run_id",
        table_name="market_discovery_candidate",
        schema="nexus",
    )
    op.drop_table("market_discovery_candidate", schema="nexus")
    op.drop_index(
        "ix_issuer_enrichment_status_provider",
        table_name="issuer_enrichment_status",
        schema="nexus",
    )
    op.drop_index(
        "ix_issuer_enrichment_status_issuer_id",
        table_name="issuer_enrichment_status",
        schema="nexus",
    )
    op.drop_table("issuer_enrichment_status", schema="nexus")
    op.drop_table("market_discovery_run", schema="nexus")
    # ### end Alembic commands ###
