"""document_extraction/document_chunk created_at: clock_timestamp() not now()

Revision ID: 0020
Revises: 0019
Create Date: 2026-08-13 12:31:50.461709

Live-caught during 10C's own integration test suite
(`test_list_for_document_orders_newest_first`): `now()` is frozen at
transaction start, so two `document_extraction` rows created in the same
transaction (a real shape — the worker's reclaim-then-claim sequence, or
any test fixture creating more than one row per connection) got an
identical `created_at` and an unstable "newest first" ordering. Same fix
`app/models/audit.py`'s `occurred_at` already applied for the identical
reason — `alembic revision --autogenerate` did not detect this
`server_default` text change (a known blind spot, see ADR-014), so both
`ALTER COLUMN ... SET DEFAULT` statements below are hand-written, not
autogenerated.

Purely a default-expression change — no data migration, no existing rows
touched (a `server_default` only affects future inserts).
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.alter_column(
        "document_extraction",
        "created_at",
        server_default=sa.text("clock_timestamp()"),
        schema="nexus",
    )
    op.alter_column(
        "document_chunk",
        "created_at",
        server_default=sa.text("clock_timestamp()"),
        schema="nexus",
    )


def downgrade() -> None:
    op.alter_column(
        "document_chunk",
        "created_at",
        server_default=sa.text("now()"),
        schema="nexus",
    )
    op.alter_column(
        "document_extraction",
        "created_at",
        server_default=sa.text("now()"),
        schema="nexus",
    )
