"""Canonical domain objects for `research_document` (PLAN.md 4.10; Milestone
10B).

See `app.models.research_document`'s module docstring for the identity-vs-
physical-storage split and the `confidentiality_classification` reuse of
`AccessClassification`.
"""

from __future__ import annotations

from datetime import date, datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict

from app.core.types import AccessClassification, ResearchDocumentType


class ResearchDocumentCreate(BaseModel):
    """Everything needed to create a `research_document` row. `id` is
    generated by the caller (`research_document_service`), not the
    database — see the ORM model's docstring for why."""

    model_config = ConfigDict(frozen=True)

    id: UUID
    issuer_id: UUID
    security_id: UUID | None = None
    document_type: ResearchDocumentType
    title: str
    description: str | None = None
    original_filename: str
    raw_payload_id: UUID
    document_date: date | None = None
    confidentiality_classification: AccessClassification = AccessClassification.STANDARD
    uploaded_by: str | None = None
    provenance_id: UUID


class ResearchDocumentMetadataUpdate(BaseModel):
    """Partial metadata edit — unset fields leave the existing value
    unchanged. Never replaces the underlying file; a new file is a new
    document (the file itself is immutable once uploaded)."""

    model_config = ConfigDict(frozen=True)

    title: str | None = None
    description: str | None = None
    document_type: ResearchDocumentType | None = None
    document_date: date | None = None
    confidentiality_classification: AccessClassification | None = None
    edited_by: str | None = None


class ResearchDocument(BaseModel):
    """A persisted `research_document` row."""

    model_config = ConfigDict(frozen=True)

    id: UUID
    issuer_id: UUID
    security_id: UUID | None
    document_type: ResearchDocumentType
    title: str
    description: str | None
    original_filename: str
    raw_payload_id: UUID
    extracted_text: str | None
    document_date: date | None
    confidentiality_classification: AccessClassification
    uploaded_by: str | None
    provenance_id: UUID
    is_archived: bool
    archived_at: datetime | None
    archived_by: str | None
    created_at: datetime
    updated_at: datetime
